--      ░▒▒▒░░░░░▓▓          ___________
--    ░░▒▒▒░░░░░▓▓        //___________/
--   ░░▒▒▒░░░░░▓▓     _   _ _    _ _____
--   ░░▒▒░░░░░▓▓▓▓▓▓ | | | | |  | |  __/
--    ░▒▒░░░░▓▓   ▓▓ | |_| | |_/ /| |___
--     ░▒▒░░▓▓   ▓▓   \__  |____/ |____/
--       ░▒▓▓   ▓▓  //____/
--
-- Migrated from the hyprlang .conf format (removed in Hyprland 0.57).
-- The old .conf files are kept on disk for reference but are no longer read.
-- See https://wiki.hypr.land/Configuring/Start/

local scrPath = os.getenv("HOME") .. "/.local/share/bin" -- set scripts path


-- █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█
-- █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄

-- Fallback for any monitor not listed below
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })

-- Was monitors.conf (generated by nwg-displays)
hl.monitor({ output = "eDP-1",     mode = "1920x1080@60.05", position = "0x0",    scale = 1.33 })
hl.monitor({ output = "HDMI-A-1",  mode = "1280x800@59.81",  position = "1444x0", scale = 2.0 })


-- █▀▀ █▄░█ █░█
-- ██▄ █░▀█ ▀▄▀

hl.env("PATH", os.getenv("PATH") .. ":" .. scrPath)
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("GDK_SCALE", "1")


-- █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
-- █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

hl.on("hyprland.start", function()
    hl.exec_cmd(scrPath .. "/resetxdgportal.sh")                                              -- reset XDPH for screenshare
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd(scrPath .. "/polkitkdeauth.sh")                                               -- authentication dialogue for GUI apps
    hl.exec_cmd("waybar")                                                                     -- launch the system bar
    hl.exec_cmd("nwg-displays --restore")                                                     -- restore monitor layout
    hl.exec_cmd("blueman-applet")                                                             -- systray app for Bluetooth
    hl.exec_cmd("udiskie --no-automount --smart-tray")                                        -- manage removable media
    hl.exec_cmd("nm-applet --indicator")                                                      -- systray app for Network/Wifi
    hl.exec_cmd("dunst")                                                                      -- start notification daemon
    hl.exec_cmd("rm -f ~/.cache/cliphist/db")                                                 -- reset cliphist id counter on login
    hl.exec_cmd("wl-paste --type text --watch cliphist -max-items 200 store")                 -- clipboard store text data
    hl.exec_cmd("wl-paste --type image --watch cliphist -max-items 50 store")                 -- clipboard store image data
    hl.exec_cmd(scrPath .. "/swwwallpaper.sh")                                                -- start wallpaper daemon
    hl.exec_cmd(scrPath .. "/batterynotify.sh")                                               -- battery notification
    hl.exec_cmd("hypridle")                                                                   -- start idle daemon
    hl.exec_cmd(scrPath .. "/waybar-autohide.sh")

    -- Was themes/common.conf + themes/theme.conf + themes/colors.conf (wallbash wins, it was sourced last)
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 20")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-size 20")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface font-name 'Inter 10'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface document-font-name 'Inter 10'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface monospace-font-name 'CaskaydiaCove Nerd Font Mono 9'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface font-hinting 'full'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-purple'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
end)


-- █ █▄░█ █▀█ █░█ ▀█▀
-- █ █░▀█ █▀▀ █▄█ ░█░

hl.config({
    input = {
        kb_layout          = "us,ara",
        kb_options         = "grp:alt_shift_toggle",
        follow_mouse       = 1,
        sensitivity        = 0,
        force_no_accel     = true,
        numlock_by_default = true,

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.device({
    name        = "epic mouse v1",
    sensitivity = -0.5,
})

-- Swiping with 3 fingers horizontally to change workspaces
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })


-- █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀
-- █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█

hl.config({
    dwindle = { preserve_split = true },
    master  = { new_status = "master" },
})


-- █▀▄▀█ █ █▀ █▀▀
-- █░▀░█ █ ▄█ █▄▄

hl.config({
    misc = {
        vrr                      = 0,
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,
        force_default_wallpaper  = 0,
    },

    xwayland = {
        force_zero_scaling = true,
    },
})


-- █▀ █▀█ █░█ █▀█ █▀▀ █▀▀
-- ▄█ █▄█ █▄█ █▀▄ █▄▄ ██▄

-- Theme, wallbash colors and animations still come from HyDE's generated
-- .conf files -- hyde-compat.lua reads them. See that file for the why.
require("hyde-compat")

require("keybindings")
require("windowrules")
require("userprefs") -- your own overrides; required last so it wins
